### ISSUE TITLE
Finish converting the old icons to svg files.

### ISSUE THREAD

**Issue by dkanada** [dkanada/ICEcons#24]
We only have 92 left and it would make adding the icon references much faster since I would only have to update one file rather than four. I have been doing them in groups of ten or so and @conrad-heimbold has added quite a few but if we focus on these icons we should have them done in a week or so.

**Comment by dkanada** [comment]
@ikocevski

**Comment by ikocevski** [comment]
How do I know which ones are alredy done/been worked on? I don't want to do unnecessary work.

**Comment by dkanada** [comment]
The icons in **/todo/old** still need to be converted, it's the same process as adding new icons but it replaces the older png files instead of creating new ones.

**Comment by dkanada** [comment]
I will be working from the middle down starting at recorder so we don't accidentally work on the same ones.

**Comment by ikocevski** [comment]
Okay, I'll just start doing them from the top. Any ideas for faster conversion? Maybe something quicker than redoing everything? Tracing maybe works?

**Comment by dkanada** [comment]
Tracing can be inaccurate I think, we have been redoing them but I have noticed it goes much faster with a completed icon to reference.

**Comment by ikocevski** [comment]
Tried tracing but either it's inaccurate or apps2org simply doesn't match with the template, don't know. I'm 90% positive that it doesn't match with the template though. Anyway what has to be done has to be done, halfway there...

**Comment by dkanada** [comment]
Wait, how are you trying to trace it? It sounds like a pain, pretty sure it would be much easier to just recreate the icon with new shapes at that point.

**Comment by conrad-heimbold** [comment]
tracing is not worth the hassle, IMHO; because the icons mostly have simple shapes which can more easily be drawn manually.

**Comment by ikocevski** [comment]
What? LOL tracing is of course easier. It just does the work for you. I just spent like a whole hour making the apps2org icon.

**Comment by conrad-heimbold** [comment]
Ok, for apps2org; tracing is probably easier.

**Comment by conrad-heimbold** [comment]
In my humble opinion, some icons by @1C3 inside /todo/old are too much different from the original app icons. E.g. for keepass2android - you don't recognize the original app icon anymore. 
I guess it's ok if we invent some new then?

**Comment by dkanada** [comment]
Yup whatever works, we should just get all of the icons finished up so we can focus on the new ones after that. If I just removed the old png files we would have a bunch of broken references in the app filter which is not ideal.

**Comment by conrad-heimbold** [comment]
@dkanada: Could you release a new app version soon, now that we are finished? Thanks for your work :)
