### ISSUE TITLE
get rid of transform + even-odd attributes and E-notation

### ISSUE THREAD

**Issue by conrad-heimbold** [dkanada/ICEcons#27]
.. because android does not support these (at least not before API level 24)

~~files that contain matrix / transform elements: 
**`android.svg, gmusic.svg, ring.svg, sensorreadout.svg, viber.svg`**~~
**EDIT 2017-07-07: No files with matrix / transform elements are left.** Please watch out and do not to create new ones! 

files that contain fill-rule:evenodd attributes: 
**`dropbox.svg, meinvodafone.svg, mgit.svg, oscilloscope.svg, sgit.svg, steam.svg`**

files that contain the E-notation for numbers: 
**`acrobat.svg, an2linux.svg, androidrun.svg, antox.svg, boinc.svg, casper.svg, contacts.svg, diaspora.svg, drive.svg, echo.svg, etar.svg, geogebra.svg, gkeyboard.svg, gmovies.svg, gsheets.svg, gslides.svg, hpprinteraio.svg, kodi.svg, kore.svg, oscilloscope.svg, practicehub.svg, riot.svg, snapseed.svg, steam.svg, whatsapp.svg, wire.svg`**

#### How to get rid of that stuff: 
* transform attributes can be integrated into pathData / **d** attribute inside **path** . I explained how to do this in issue #20 , comment 2 . 
* fill-rule:even-odd attributes can be safely omitted, AFAIK. 
* E-notation should be converted to normal notation. 

In my humble opinion; fixing transform attributes should get priority, then even-odd; then E-notation.

**Comment by dkanada** [comment]
I have mostly figured out how to avoid transform and fill-rule elements but I have never heard of e-notation, what causes that? You are correct, for these icons we can completely avoid using anything other than paths and shapes, nothing else should be needed since the icons are so simple. I have been removing the fill-rule elements when I see them.

**Comment by conrad-heimbold** [comment]
@dkanada E-notation is only used for either really big numbers (which we don't have); or really small numbers (which we do have). More information on the scientific E-notation: https://en.wikipedia.org/wiki/Scientific_notation#E-notation 
I would speculate, we can replace all occurences of these E-numbers with just 0 , because the numbers are so small that it doesn't make a difference.

**Comment by dkanada** [comment]
Did you use a script to find the instances listed above? Could you add that script the the repo, it would be a useful tool to have. Also, what's the status right now for this issue, I am not sure how many items are left here.

**Comment by conrad-heimbold** [comment]
@dkanada **matrix / transform** elements should all be done. The rest is still to be done. 
I didn't use a script to find these files; instead I used **svg2android** in the browser (see issue #26), which gave me a **log.html** file that contained the listed info from above.

**Comment by conrad-heimbold** [comment]
All fixed by pull request #58!
