### ISSUE TITLE
Rename all icons + references to CamelCase / Uppercase

### ISSUE THREAD

**Issue by conrad-heimbold** [dkanada/ICEcons#29]
Android doesn't like dashes and whitespace, underscore looks ugly; so we are forced to use CamelCase / uppercase.

**Comment by ikocevski** [comment]
Isn't camelCase done like this? I'm pretty sure 😀

**Comment by dkanada** [comment]
yup

**Comment by conrad-heimbold** [comment]
<image src="https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/CamelCase.svg/1240px-CamelCase.svg.png"/>

**Comment by ikocevski** [comment]
It's a matter of preference then, so, whatever works as @dkanada would say 😁
