### ISSUE TITLE
com.android.musicfx Icon Request (default equaliser)

### ISSUE THREAD

**Issue by fredddii** [dkanada/ICEcons#36]
A default application in OmniROM 7.1.2.

![ljusiab](https://user-images.githubusercontent.com/15217150/27650241-9c68ca20-5c34-11e7-9f48-29738eb9ad39.png)

**Comment by conrad-heimbold** [comment]
Sorry, that doesn't help us very much - we need both: 
- the app (package) name
- **and** the main activity name, which gets launched when opening the app from your home screen

Please 
- either use **Turtl** (search for it on F-Droid) to get both the package and activity name for the app
- or find the correct app and activity name for the app with **ApplicationsInfo** (search for it on F-Droid)

**Comment by fredddii** [comment]
Turtl:
[20170629_045629.zip](https://github.com/dkanada/ICEcons/files/1110776/20170629_045629.zip)

**Comment by conrad-heimbold** [comment]
@freddii : we (dkanada , ikocevski, me) have star'ed this repo (ICEcons), so every time, when somebody opens an issue here; we get a notification by E-mail. 

So today, we got more than 15 E-mails from you, one for every issue and comment. Please keep that in mind when creating issues / comments!

**Comment by freddii** [comment]
fredddi postet that messages not freddii (me) three d's  freddi posted them

**Comment by conrad-heimbold** [comment]
@freddii : sorry 'bout that
