### ISSUE TITLE
org.codeaurora.snapcam Icon Request (default camera)

### ISSUE THREAD

**Issue by fredddii** [dkanada/ICEcons#37]
Default camera application that comes with OmniROM 7.1.2.

![cenhuwf](https://user-images.githubusercontent.com/15217150/27650755-3053c2f2-5c36-11e7-8315-e6811c4091ef.png)

**Comment by conrad-heimbold** [comment]
Sorry, that doesn't help us very much - we need both: 
- the app (package) name
- **and** the main activity name, which gets launched when opening the app from your home screen

Please 
- either use **Turtl** (search for it on F-Droid) to get both the package and activity name for the app
- or find the correct app and activity name for the app with **ApplicationsInfo** (search for it on F-Droid)

**Comment by fredddii** [comment]
Turtle: 
[20170629_045444.zip](https://github.com/dkanada/ICEcons/files/1110774/20170629_045444.zip)
