### ISSUE TITLE
com.android.quicksearchbox Icon Request (default search)

### ISSUE THREAD

**Issue by fredddii** [dkanada/ICEcons#38]
Default application that comes with OmniROM 7.1.2.

![qwrvx8d](https://user-images.githubusercontent.com/15217150/27650843-8a7402a6-5c36-11e7-88ce-5a965c432a0a.png)

**Comment by conrad-heimbold** [comment]
Sorry, that doesn't help us very much - we need both: 
- the app (package) name
- **and** the main activity name, which gets launched when opening the app from your home screen

Please 
- either use **Turtl** (search for it on F-Droid) to get both the package and activity name for the app
- or find the correct app and activity name for the app with **ApplicationsInfo** (search for it on F-Droid)

**Comment by fredddii** [comment]
Turtl:
[20170629_045751.zip](https://github.com/dkanada/ICEcons/files/1110778/20170629_045751.zip)
