### ISSUE TITLE
org.omnirom.deskclock Icon Request

### ISSUE THREAD

**Issue by fredddii** [dkanada/ICEcons#41]
Default application in OmniROM 7.1.2 that provides clock functionality.

![w81avaj](https://user-images.githubusercontent.com/15217150/27651251-fad7a74a-5c37-11e7-8037-df9fb5650a3f.png)
![buhfskp](https://user-images.githubusercontent.com/15217150/27651252-fad886ce-5c37-11e7-9909-16d2f03c1e88.png)

**Comment by conrad-heimbold** [comment]
Sorry, that doesn't help us very much - we need both: 
- the app (package) name
- **and** the main activity name, which gets launched when opening the app from your home screen

Please 
- either use **Turtl** (search for it on F-Droid) to get both the package and activity name for the app
- or find the correct app and activity name for the app with **ApplicationsInfo** (search for it on F-Droid)

**Comment by fredddii** [comment]
Turtl:
[20170629_050137.zip](https://github.com/dkanada/ICEcons/files/1110786/20170629_050137.zip)
