### ISSUE TITLE
me.phh.superuser Icon Request

### ISSUE THREAD

**Issue by fredddii** [dkanada/ICEcons#42]
Provides root management functionality.

![yovjirv](https://user-images.githubusercontent.com/15217150/27651713-8e4dc9fe-5c39-11e7-8a83-e0074f49f0dd.png)
![bai5ugj](https://user-images.githubusercontent.com/15217150/27651712-8e4a9c34-5c39-11e7-8a3e-0acc43623844.png)
![3lgo53a](https://user-images.githubusercontent.com/15217150/27651711-8e265cd4-5c39-11e7-9fe6-c2ac2e271fe4.png)

**Comment by conrad-heimbold** [comment]
Sorry, that doesn't help us very much - we need both: 
- the app (package) name
- **and** the main activity name, which gets launched when opening the app from your home screen

Please 
- either use **Turtl** (search for it on F-Droid) to get both the package and activity name for the app
- or find the correct app and activity name for the app with **ApplicationsInfo** (search for it on F-Droid)

**Comment by fredddii** [comment]
Turtl:
[20170629_050246.zip](https://github.com/dkanada/ICEcons/files/1110789/20170629_050246.zip)
