### ISSUE TITLE
Icons not assigned to the right app/package name?

### ISSUE THREAD

**Issue by i-kocevski** [dkanada/ICEcons#8]
I'm using the default Trebuchet launcher on CM11 and some icons that are already present in the pack don't actually theme the apps. For example Kore and VSCO.

**Comment by dkanada** [comment]
As apps are updated their package names sometimes change, so even if I have an icon assigned to a specific package name it could not have an the new one as well. If you get me the new component names I will add them to the app for the next release.

**Comment by i-kocevski** [comment]
Yeah, I am aware of that. Just reporting some "mini-bugs" as a user here, not blaming you.

So, here are the package names:
VSCO - com.vsco.cam
Kore (The official Kodi remote) - org.xbmc.kore

I looked them up via oandbackup and their Play Store links just to be sure. Cheers!

**Comment by dkanada** [comment]
Actually I need the component names which are slightly different and include the activity that is first launched when you open an app. You can find that by looking at the text below the app names in [turtl](https://f-droid.org/app/org.xphnx.iconsubmit) or some other way.

**Comment by i-kocevski** [comment]
Okay, so I installed turtl and I have the proper eyes now :D

org.xbmc.kore/org.xbmc.kore.ui.sections.remote.RemoteActivity

com.vsco.cam/com.vsco.cam.navigation.LithiumActivity

**Comment by dkanada** [comment]
Should be fixed now, let me know if you still have the wrong icons after the update, and no problem, just glad to make a decent icon pack for F-Droid.
