### ISSUE TITLE
[question] switch to scour for optim instead of svgo, inkscape can't handle some svgo optim

### ISSUE THREAD

**Issue by conrad-heimbold** [dkanada/ICEcons#9]
This is almost certainly a bug on the side of Inkscape. 

Some files that have been optimized with svgo, can not be handled / viewed / edited anymore with Inkscape. 

Opening / viewing those files works perfectly with eog (eye of gnome) / gthumb. This is definitely a bug on the side of Inkscape; but I could not yet figure out where the problem is exactly. When optimizing with scour, I never had such problems. 

Examples: 
![inkscape_bug_example_1](https://cloud.githubusercontent.com/assets/17474312/26639326/ca253910-4624-11e7-8a4d-4c0066fce6e3.png) 
![inkscape_bug_example_2](https://cloud.githubusercontent.com/assets/17474312/26639343/d4b740a8-4624-11e7-8b0d-b534bf85d1f9.png)

Do you know which optimisations cause the problems? Then I could make the bug report for Inkscape more detailed. Until this bug on the side of Inkscape gets fixed, could we maybe switch to scour for optimizing? Scour is not as comfortable as svgo (e.g. no svgo folder functionality via -f), but gets things done as well.

**Comment by dkanada** [comment]
Huh I have no clue how that is happening. Icons you have added after using scour look exactly the same as the ones I clean with svgo. Maybe try running git pull? I just tried opening the messaging and openvpn icons and they looked fine to me. I have noticed that a bunch of issues crop up with the icons when the svg files contain viewBox and transform fields, but that is more of a problem with the svg spec than inkscape.

**Comment by conrad-heimbold** [comment]
- stable inkscape version 0.92 from dnf on Fedora crashs when opening second svg file (bug report: https://bugs.launchpad.net/inkscape/+bug/1694314 )
- development inkscape version 0.92 from snap on Fedora can't run because libmir is not found (obviously - I am not on Ubuntu)
- default inkscape version 0.91 from apt on Ubuntu can't handle files optimized with svgo
- development version of inkscape from https://copr.fedorainfracloud.org/coprs/ryanlerch/inkscape-devel/packages/ can't be installed, because the build failed. 
- inkscape flatpak package for Fedora requires Gnome 3.20, I have got Gnome 3.22. 
- Let's see if I can install Inkscape development version on Ubuntu via snap...
Really frustrating...

**Comment by conrad-heimbold** [comment]
Just FYI: inkscape version 0.92 does not seem to have the mentioned issue, only version 0.91.

**Comment by dkanada** [comment]
Yeah, linux is really nice until you find that one program that has a stubborn issue and then suddenly you're hunting down like eight different packages and fifteen dependencies to get something working. I still haven't found an app with an external build step that didn't completely fail due to some crash or missing program in android studio.

**Comment by dkanada** [comment]
Do you have an xmpp account? We can converse over over Conversations if you have one.

**Comment by dkanada** [comment]
Just added scour to the script instead of svgo so this shouldn't be an issue for new icons anymore.
